version: '3'
services:
  db:
    container_name: tabungan-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tabungan_api_db
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql